# Generated by Django 6.0 on 2026-01-15 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('district', models.CharField(blank=True, choices=[('akkar', 'Akkar - عكار'), ('aley', 'Aley - عاليه'), ('baabda', 'Baabda - بعبدا'), ('baalbek', 'Baalbek - بعلبك'), ('batroun', 'Batroun - البترون'), ('beirut', 'Beirut - بيروت'), ('bint_jbeil', 'Bint Jbeil - بنت جبيل'), ('bsharri', 'Bsharri - بشري'), ('byblos', 'Byblos - جبيل'), ('chouf', 'Chouf - الشوف'), ('danniyeh', 'Danniyeh - الضنية'), ('hasbaya', 'Hasbaya - حاصبيا'), ('hermel', 'Hermel - الهرمل'), ('jezzine', 'Jezzine - جزين'), ('keserwan', 'Keserwan - كسروان'), ('koura', 'Koura - الكورة'), ('marjeyoun', 'Marjeyoun - مرجعيون'), ('matn', 'Matn - المتن'), ('nabatieh', 'Nabatieh - النبطية'), ('rashaya', 'Rashaya - راشيا'), ('sidon', 'Sidon - صيدا'), ('tripoli', 'Tripoli - طرابلس'), ('tyre', 'Tyre - صور'), ('western_bekaa', 'Western Bekaa - البقاع الغربي'), ('zahle', 'Zahle - زحلة'), ('zgharta', 'Zgharta - زغرتا')], max_length=50)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
