# Generated by Django 6.0 on 2026-01-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='building_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
