# Generated by Django 6.0 on 2026-01-22 09:13

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_userprofile_building_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='LB'),
        ),
    ]
