# Generated by Django 6.0 on 2026-01-22 09:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_userprofile_phone_userprofile_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='LB'),
        ),
    ]
