# Generated by Django 6.0 on 2026-01-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Not Confirmed'), ('confirmed', 'Confirmed')], max_length=20),
        ),
    ]
