# Generated by Django 6.0 on 2026-01-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('take_from_store', 'Take From Store')], default='delivery', max_length=20),
        ),
    ]
