# Generated by Django 6.0 on 2026-01-15 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='John@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='John Doe', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='+91xxxxxxxxxx', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, choices=[('akkar', 'Akkar - عكار'), ('aley', 'Aley - عاليه'), ('baabda', 'Baabda - بعبدا'), ('baalbek', 'Baalbek - بعلبك'), ('batroun', 'Batroun - البترون'), ('beirut', 'Beirut - بيروت'), ('bint_jbeil', 'Bint Jbeil - بنت جبيل'), ('bsharri', 'Bsharri - بشري'), ('byblos', 'Byblos - جبيل'), ('chouf', 'Chouf - الشوف'), ('danniyeh', 'Danniyeh - الضنية'), ('hasbaya', 'Hasbaya - حاصبيا'), ('hermel', 'Hermel - الهرمل'), ('jezzine', 'Jezzine - جزين'), ('keserwan', 'Keserwan - كسروان'), ('koura', 'Koura - الكورة'), ('marjeyoun', 'Marjeyoun - مرجعيون'), ('matn', 'Matn - المتن'), ('nabatieh', 'Nabatieh - النبطية'), ('rashaya', 'Rashaya - راشيا'), ('sidon', 'Sidon - صيدا'), ('tripoli', 'Tripoli - طرابلس'), ('tyre', 'Tyre - صور'), ('western_bekaa', 'Western Bekaa - البقاع الغربي'), ('zahle', 'Zahle - زحلة'), ('zgharta', 'Zgharta - زغرتا')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
