# Generated by Django 6.0 on 2026-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('returned', 'Returned'), ('confirmed', 'Confirmed')], max_length=20),
        ),
    ]
