# Generated by Django 6.0 on 2026-01-19 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Up to 15 digits allowed, can start with +.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
