# Generated by Django 6.0 on 2026-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_customer_phone_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='building_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
