# Generated by Django 6.0 on 2026-01-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True),
        ),
    ]
