# Generated by Django 6.0 on 2025-12-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
