# Generated by Django 6.0 on 2026-01-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
