# Generated by Django 6.0 on 2026-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_stockmovement_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
